- hosts: server
  become: yes
  become_user: pau

  vars_files:
    - ./vars/vars.yaml

  tasks:

    - name: Install pip3
      apt: 
        name:
          - python3-pip

    - name: Install pip3 kubernetes package
      pip:
        name: kubernetes