apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: nextsync
type: Opaque
data:
  MYSQL_DATABASE: bmV4dGNsb3Vk 
  MYSQL_USER: bmV4dGNsb3Vk 
  MYSQL_PASSWORD: MXpqZjExUGc4ZU1SdzREWAo=
  MYSQL_ROOT_PASSWORD: aEtHOGJjUkR4NG9WZDNndwo=