apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextsync-pvc
  namespace: nextsync
spec:
  storageClassName: openebs-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3G
  volumeName: nextsync